# reproducibility
seed: 42

model_name: ${model_name}  # used to name the directory in which model's checkpoints will be stored (experiments/model_name/...)
project_name: coreference_resolution_project  # used to name the project in wandb
export: False

# pl_trainer
pl_trainer:
  _target_: pytorch_lightning.Trainer
  log_every_n_steps: 9
  accelerator: gpu
  devices: 1
  num_nodes: 1
  strategy: null
  accumulate_grad_batches: 4
  gradient_clip_val: 1.0
  val_check_interval: 0.3  # you can specify an int "n" here => validation every "n" steps
  max_epochs: 100
  deterministic: True
  fast_dev_run: False
  precision: 32

# early stopping callback
# "early_stopping_callback: null" will disable early stopping
early_stopping_callback:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: val/full_loss
  mode: min
  patience: 10

# model_checkpoint_callback
# "model_checkpoint_callback: null" will disable model checkpointing
model_checkpoint_callback:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: val/full_loss
  mode: min
  verbose: True
  save_top_k: 1
  filename: 'checkpoint-val_loss_{val/full_loss:.4f}-epoch_{epoch:02d}'
  auto_insert_metric_name: False
